### ISSUE TITLE
Add missing copy_popper(T const&) ctor for ring_span

### ISSUE THREAD

**Issue by martinmoene** [WG21-SG14/SG14#102]
Missing from both proposal and reference code.

**Comment by Quuxplusone** [comment]
This is fixed in b08b6abe270fe201303d0ab53be64541eacac3a6 (in my fork, no pull request yet), by replacing the `copy_popper(T&&)` constructor with a single `copy_popper(T)` constructor. The take-ctor-parameters-by-value idiom isn't widely used by the STL (yet?), but we're already using it elsewhere in this header, so personally I think it's fine.
