### ISSUE TITLE
inplace_function doesn't handle arguments with rvalue references well

### ISSUE THREAD

**Issue by sleep-deprived** [WG21-SG14/SG14#154]
For example, see here: https://godbolt.org/z/U3a2GX

```
#include <string>
#include "inplace_function.h"

std::string global_dummy;
void take(std::string&& s)
{
    global_dummy = std::move(s);
}

int main() 
{
    /// comment this and uncomment the std::function line to make it compile
    stdext::inplace_function<void(std::string&&)> func(take);
    //std::function<void(std::string&&)> func(take);

    std::string s = "1234567";
    func(std::move(s));
}
```

This code works as expected with std::function, but doesn't compile with inplace_function, complaining that (exact phrasing depends on compiler, but the same error message appears in all of them):
 
> error: cannot bind rvalue reference of type 'std::__cxx11::basic_string<char>&&' to lvalue of type 'std::__cxx11::basic_string<char>'

If I understand it correctly, the problem is that operator() can't use a forwarding reference for the function arguments because they are not deduced in the function (they are parameters of the class template).

The standard library implementations solve this somehow. This rabbit hole was too complicated for me to follow.

**Comment by Quuxplusone** [comment]
> If I understand it correctly, the problem is that operator() can't use a forwarding reference for the function arguments because they are not deduced in the function (they are parameters of the class template).

Not really. The forwarding references are correct (although you are *also* correct that they're not "forwarding" references in the most common flavor). The bug was that in one place there was a lambda of the form

    [](storage_ptr_t storage_ptr, Args&&... args)
            noexcept(noexcept(std::declval<C>()(args...))) -> R
    {
        return (*static_cast<C*>(storage_ptr))( std::forward<Args>(args)... );
    }

Notice that it takes (pseudo-)forwarding references, and calls `std::forward` on them in the body of the function, but ***the `noexcept`-specification uses `args` without `std::forward`!*** This triggers the hard error you were seeing.

I fixed this by adding the missing `std::forward` in cb660209be16335db270b90ccaf67fcc3d7a0714, and then on second thought decided to remove the offending `noexcept`-specification entirely in 76784f809cddfd7b8d66a8ec8b0be5f5ce64ae2d — it wasn't serving any functional purpose except to gather bug reports. :P [I've written before on how nobody gets `noexcept`-specifications right, including myself.](https://quuxplusone.github.io/blog/2018/06/12/attribute-noexcept-verify/#the-upside)
