### ISSUE TITLE
[inplace_function.h] Copyright holder

### ISSUE THREAD

**Issue by daichifukui** [WG21-SG14/SG14#174]
Hi.

Can you help me determine the copyright holder of inplace_function.h?

The Boost Software License, which is applied to inplace_function.h, clearly states that "the copyright notices in the Software ... must be included in all copies of the Software".
However, there is no copyright notice embedded in that header file.
There is plf_licensing.txt under the Docs directory, but it's not clear that licensing file applies to inplace_function.h.

Best,
Fukui

**Comment by TBBle** [comment]
We don't have any copyright assignment system for this repo. @carlcook and @nidoizo are the original authors of that code, (and [the paper it is implementing](https://github.com/WG21-SG14/SG14/blob/master/Docs/Proposals/NonAllocatingStandardFunction.pdf)) in 2016, and it has been touched since by @Voultapher and @Quuxplusone. So the copyright would fall amongst them.

There may also be some copyright expectations or understandings for papers submitted to the ISO WG21 and their associated code examples; again, I don't know. I don't believe the paper was ever formally submitted either, [it's not indexed by the mailing list archive](https://wg21.link/p0419).

I'm not an IP lawyer, so I don't really know what copyright statement (if any) you could or should synthesize here.

At this point, there are "no copyright notices in the Software" so if I were pulling this into a code-base, I'd say there's nothing to include (although that doesn't affect the actual copyright status), but would definitely record where and how I sourced it for auditability.

plf_licensing.txt is indeed unrelated, it relates only to code implementing the `plf` namespace as noted at the top of that file.

**Comment by Quuxplusone** [comment]
> There may also be some copyright expectations or understandings for papers submitted to the ISO WG21 and their associated code examples; again, I don't know.

I don't think there are any relevant expectations/demands in that department. I don't know about ISO, but INCITS (the U.S. organization) simply requires that authors grant ITI a license to use their contributions "solely for the purpose of developing and publishing the [Standard]," and then INCITS further sublicenses their own content "on condition that this is not done for profit, that no changes are made to the documents, and that ITI's rights in the documents are acknowledged." Both of those steps seem designed specifically to _avoid_ necessarily granting anyone else the right to use or derive-from the author's work. So, the mere fact that a thing has been submitted to ISO (which, as you point out, `inplace_function` never was, anyway) doesn't seem likely to be relevant from a _legal_ standpoint.

Of course I, also, am not a lawyer.

> At this point, there are "no copyright notices in the Software" so if I were pulling this into a code-base, I'd say there's nothing to include (although that doesn't affect the actual copyright status)

Agreed. The Boost license requires you to preserve the license itself, plus the set of all the copyright notices in the file (which currently is a set with cardinality zero). I doubt there's any legal need to synthesize a "Copyright (c) _some date_ _some authors_" statement anywhere.

If SG14 really wants to preserve (the URL of) a record of historical authorship, the simplest way might be to add a line like

    // Copyright: the contributors listed at https://github.com/WG21-SG14/SG14/

(which, being phrased as a "copyright notice," can't be removed); but at the same time, it's not terribly clear what such a copyright notice actually _means_, which might make it actually worse than useless, legally speaking, if anybody were ever to care about its legal meaning.

**Comment by daichifukui** [comment]
Hi all,

Thanks for the feedback.

The background of this issue is that dissemination of copyright holders is required for a debian/copyright file.
Based on your comments, with the help of a debian developer, we managed to upload a copyright file as follows:
https://salsa.debian.org/debian/jsonnet/-/blob/debian/0.18.0+ds-1/debian/copyright#L46

Now that the copyright file is committed, I think it is a good time to close this issue.

Best,
Fukui
