### ISSUE TITLE
Switch to a real unit-test framework

### ISSUE THREAD

**Issue by TBBle** [WG21-SG14/SG14#96]
A problem I just discovered with the current `assert`-based testing is that the tests disappear in Release (or RelWithDebInfo) builds.

I'd suggest [Catch](http://catch-lib.net) since it's single-header, has reasonable clear syntax, and supports good DRY behaviours and BDD terminology.

I'm also happy to go ahead and do the conversion, this would help clean-up the current tests which are lumped together into a single executable, and one test currently prompts the user for input.

I'd probably go ahead and restructure the CMake a bit too, to take advantage of unit-testing support and allow testing individual tests. Currently compile failures in one test block the other tests completely.

**Comment by TBBle** [comment]
As mentioned, I'm happy to do the work here. I'd just like some feedback from @WG21-SG14 that it won't be wasted effort because we don't want to introduce such external dependencies, for example.

**Comment by martinmoene** [comment]
[Aside: I'm working on a `ring_span` for use with C++98 and later that aims to follow the interface of the emerging `std::[exerimental::]ring_span` insofar possible. It's called [ring-span lite](https://github.com/martinmoene/ring-span-lite). There are the beginnings of a [test specification](https://github.com/martinmoene/ring-span-lite/blob/master/test/ring-span.t.cpp), section in [Readme](https://github.com/martinmoene/ring-span-lite#a1-variant-lite-test-specification).]

**Comment by mattreecebentley** [comment]
Hey, 
I don't think it's useful or necessary to switch to an actual test framework, the reason why I avoided doing so for colony etc is because there's no reason to import a framework when a 10 line function will do.
Also I'm aware of creating technical barriers to people wanting to contribute, even if those barriers are small.
In terms of the actual problem, I agree with you, and switching those lines to something referencing:

#define D_assert(condition) \
		{ \
			if (!(condition)) \
			{ \
				std::clog << "Assertion `" #condition "` failed in " << __FILE__ << " line " << __LINE__ << ". " << std::endl; \
				std::clog.flush(); \
				std::exit(EXIT_FAILURE); \
			} \
		}

, or similar would be fine from my viewpoint.

**Comment by TBBle** [comment]
Some issues I have with the assert-based approach.

The first failure terminates your test run.

I also find that with a huge pile of 10-line functions, it's much harder to see the gaps in coverage (c.f. #93 and #94 which indicate that we have non-compilable or non-linkable constructs hidden in `ring_span` in places the current tests don't cover).

And creating a variant of a test with different control flow requires either putting loops in your test (which means the basic assertion doesn't tell you *which* iteration you were on), building a loop across a big `if` (which is just noise when you're reading), or repeating your whole test setup and initial steps until you get to the diverging stage.

**Comment by TBBle** [comment]
I personally don't consider putting `GIVEN` or `TEST_CASE` on the front of a function instead of modifying main.cpp to list your test method, and then replacing `<cassert>` with `"catch.hpp"` and `assert` with `REQUIRE` to be technical barriers to writing tests. It actually seems *lower-friction* to me.

Specifically, this ticket came about because I want to add more tests, but the current layout is high-friction around main.cpp and testing multiple similar paths without having to iterate on multiple different functions at once.

I particularly dislike the alternative of building up a collection of locally-created macros for the same effect, but which no one outside the project will have seen before.

**Comment by martinmoene** [comment]
My pledge would be to have one test case per function, using function names that describe the expectation, like:
```
Allows_to_construct_a_full_span_from_an_iterator_pair() {...}
Allows_to_move_construct_from_a_ring_span_of_the_same_type() {...}
```
or like
```
A_ring_span_constructed_from_an_iterator_pair_is_full()  {...}
...
```

Within each function generally three section:
- setup
- behaviour to test
- assertion of expectation

See for example Kevlin Henney's [What We Talk About When We Talk About Unit Testing](https://www.infoq.com/presentations/unit-testing-tips-tricks) ([slides](https://www.slideshare.net/Kevlin/what-we-talk-about-when-we-talk-about-unit-testing)).

**Comment by mattreecebentley** [comment]
No. I'm just going to say outright No to all of this.
Individual authors should be able to define a testing strategem that works for them. If there are faults in their individual tests, those should be pointed out to them. But the further we move from that, and the closer to standardising, the more we make this a formalized collection, rather than a series of individual proposals, which is, actually, what it is.
And what seems innocuous and low-friction in the short-term, leads to accretion in the long-term. That is exactly the opposite of what you want if you want to encourage people to come up with new, interesting ideas - because typically the people who come up with new ideas are the less-experienced ones.
The tests are not important. What is important is the technology they test. Please focus on that.

**Comment by mattreecebentley** [comment]
ps. This is not intended to discourage you from contributing to the repository - but please do so by respecting the author's(s) individual style, rather than attempting to express your own.

**Comment by TBBle** [comment]
Okay, we may be on different tracks then. My understanding was that this *is* a formalised collection ("a library") of useful library stuff, which are in-process of being standardised.

Hence the repo description, _A library for Study Group 14 of Working Group 21 (C++)_, and the fact they're all sitting in the same directory, and with tests also sitting in a shared directory.

**Comment by martinmoene** [comment]
I've made provisions in [ring-span-lite](https://github.com/martinmoene/ring-span-lite) to test the [SG14 `ring_span` reference implementation](https://github.com/WG21-SG14/SG14/blob/master/SG14/ring.h)

Results so far (`span_iterator`) not yet covered):

- VC15 19.10.25017 (VS2017): 
  - tests so far pass
- GNU C++ 6.3.0: 
  - doesn't compile: requires `difference_type operator-(type const& lhs, type const& rhs)`
  - provided `sg14::swap()` myself

**Comment by TBBle** [comment]
Just to clarify my intentions: if a particular library author doesn't want their code to use a real testing framework, that's not an issue per-se. That makes a lot of sense for authors like @mattreecebentley who're pulling code over from another repository anyway, as the discussion would need to happen there, rather than here.

So this issue was mainly intended to be a suggestion to the library authors, and an offer to take care of the once-off cost. It's convenient if I do multiple at-once, but by no-means necessary. I'm waiting for feedback from other authors before I go off and do anything anyway; my main interest lies in getting things buildable so I can point something like Travis and/or AppVeyor at the system and be able to see that they're always buildable and passing their tests. (This is also why I re-opened this ticket. I've only had one voice so far, but that's not the end of the offer.)

I do think that consistency holds great benefit, and when things are standardised, they're going to be made consistent anyway (once LWG gets hold of them, if not before), but that's not my primary goal here.

Lack of consistency and lack of a useful testing framework does limit my contributions here, but not in a way that is going to block anyone, or really cost me any time. They might mess with my ability to use the SG14 library in work projects, but that's not a major issue at this time.

**Comment by Quuxplusone** [comment]
I do think it would be valuable to stick to "good, clean" unit tests as much as possible; i.e., it would be nice if the main testing binary didn't (A) require user input on stdin and (B) take more than a second to run, both of which are true right now because of (A) ring_test and (B) unstable_remove_test respectively.  Splitting out an "interactive REPL" binary and/or a "benchmarks" binary separately from the "tests" binary would be a welcome improvement IMHO, regardless of whatever happens to the syntax of the test source files.

As for switching to Boost.UnitTest or GTest or Catch or whatever...  I think as long as it's a single-header library with not-too-heavyweight syntax, I'd be in favor of it. Does anyone have strong opinions about https://github.com/philsquared/Catch versus https://github.com/martinmoene/lest versus https://github.com/onqtam/doctest versus...?

**Comment by TBBle** [comment]
Clarified on the reflector, I did have the wrong end of the stick about the SG14 repo. The offer stands if anyone wants their existing unit tests Catchified or doctestified or lestified.

I have only used Catch before, but all three of these appear on a brief glance as strong contenders that I'd be happy to use. Having @martinmoene here if things go wrong seems like a point in favour of lest. ^_^

**Comment by Quuxplusone** [comment]
FWIW @TBBle I'd love the ring tests to be somethingified, for some value of "somethingified". Separately, I'll submit a patch probably next week to remove the dependency on `stdin` from that one ring test, if you don't beat me to it. Separately x2, I'd love commit privileges. ;)

**Comment by TBBle** [comment]
@Quuxplusone Your name's on the paper, so I've sent you an invite for commit privileges on the SG14 repo. Tagging @hatcat since I don't know who's holding the paper draft source, so you guys will need to make sure it's kept up-to-date with the evolving API.

**Comment by p-groarke** [comment]
I will be sending a PR with "real" unit tests once CI is done. Is there a consensus on what library you want to use?

I would personally recommend gtest through conan. But that adds a dependency to conan.
We could do catch and download the header through cmake config (another robust solution).
Or simply commit catch in the repo.
The only thing I would oppose to is submodules.

**Comment by Quuxplusone** [comment]
I would strongly prefer something that does **not** require me to download extra dependencies in order to build and test locally. (Right now I'm using `-DTEST_MAIN` so that I don't even need CMake locally!) If you are sure that your new dependency is available via both "apt-get" on Ubuntu and "brew install" on OSX, then I am only _mildly_ opposed to it.

An external dependency would need a really stable API; I'd like to avoid the failure mode of "Alice commits code that depends on version Bleeding.Edge of the dependency; it works on CI with a freshly curled dependencies, but causes annoying build issues for Bob who hasn't upgraded packages this month yet."

Therefore I would prefer the solution to be checked into the repo: either a header-only solution (e.g. Catch, but I don't mean that as a specific endorsement), or a completely homebrew solution (e.g., a ten-line header "sg14-assert.h" that defines an `ASSERT` macro). I am also happy with the existing practice using `assert()`, even though I admit it has weird interactions with "release mode" (`-DNDEBUG`).

For my information, why are you specifically opposed to using submodules here? — the incessant security vulnerabilities ([CVE 2017-1000117](https://www.cvedetails.com/cve/CVE-2017-1000117/), [CVE 2018-11235](https://blogs.msdn.microsoft.com/devops/2018/05/29/announcing-the-may-2018-git-security-vulnerability/), [CVE 2018-17456](https://blog.github.com/2018-10-05-git-submodule-vulnerability/) ...), or some concern about their portability, or something else?

**Comment by p-groarke** [comment]
@Quuxplusone I'll go with catch checked in the repo. It is a pretty well known testing framework, which has plenty of benefits in and of itself.

For submodules, it is personal taste and bad experience. I find them unintuitive, error prone and not well suited for external dependencies. An argument can be made for internal dependencies, which is really what they were created for. Using conan/cmake for tracking your external dependencies is much much more robust and transparent for the end user (again, in my humble opinion).

**Comment by johnmcfarlane** [comment]
+1

Dependencies tests is not nearly as restrictive as dependencies for the
final product. I think having a test framework required by developed -- as
opposed to users -- is not unreasonable.

What about ExternalProject_Add for CMake builds? Is that any less of a
security concern?

**Comment by p-groarke** [comment]
Cmake's external project is robust, but the counter argument is some people aren't using cmake to build the tests. They would have to download the catch header and put it in their header search path or add it to their command manually.

**Comment by pdimov** [comment]
Just a drive-by comment that the original problem of `assert`-based tests disappearing in release builds can be solved by `#undef NDEBUG` on the first line of the test .cpp files.

**Comment by mattreecebentley** [comment]
This's been raised before in the past and determined to be antithetical to the goals of SG14. Closing this now.
